fermisurfer: bz_lines.cpp File Reference
bz_lines.cpp File Reference
Compute lines of BZ boundary.
#include "basic_math.hpp"
#include "variable.hpp"
#include <wx/wx.h>
#include <cstdlib>
#include <cstdio>
#include <cmath>
Functions
static int bragg_vert (GLfloat bragg[26][3], GLfloat brnrm[26], int ibr, int jbr, int nbr, GLfloat vert[3], GLfloat vert2[3])
Judge wheser this line is the edge of 1st BZ.
static void check_bragg ()
Compute real number of Bragg plane at 1st BZ.
void bz_lines ()
Compute Brillouin zone boundariy lines.
Detailed Description
Compute lines of BZ boundary.
Definition in file bz_lines.cpp.
Function Documentation
bragg_vert()
static int bragg_vert (GLfloat bragg[26][3], GLfloat brnrm[26], int ibr, int jbr, int nbr, GLfloat vert[3], GLfloat vert2[3]) static
Judge wheser this line is the edge of 1st BZ.
Parameters
[in] ibr [in] Index of a Bragg plane
[in] jbr [in] Index of a Bragg plane
[in] nbr [in]
[in] vert [in] start point of line
[in] vert2 [in] end point of line
Definition at line 45 of file bz_lines.cpp.
References bragg, brnrm, and solve3().
Referenced by bz_lines().
bz_lines()
void bz_lines ()
Compute Brillouin zone boundariy lines.
Modify : nbzl, bzl
Definition at line 163 of file bz_lines.cpp.
References bragg, bragg_vert(), brnrm, bzl, check_bragg(), and nbzl.
Referenced by MyApp::OnInit().
check_bragg()
static void check_bragg () static
Compute real number of Bragg plane at 1st BZ.
Then, compute real number Bragg plane of 1st BZ (nbragg), Re-order bragg and brnrm
Definition at line 111 of file bz_lines.cpp.
References bragg, brnrm, bzl, nbragg, nbzl, and terminal.
Referenced by bz_lines().