fermisurfer: TestGLCanvas Class Reference
TestGLCanvas Class Reference
#include <operation.hpp>
Public Member Functions
TestGLCanvas (wxWindow *parent, wxWindowID id=wxID_ANY, int *gl_attrib=NULL)
virtual ~TestGLCanvas ()
void OnPaint (wxPaintEvent &event)
Glut Display function called by glutDisplayFunc.
void OnSize (wxSizeEvent &event)
void OnChar (wxKeyEvent &event)
Glut special key function.
void OnMouseEvent (wxMouseEvent &event)
Glut mouse function.
void InitGL ()
Private Member Functions
wxDECLARE_NO_COPY_CLASS (TestGLCanvas)
wxDECLARE_EVENT_TABLE ()
Private Attributes
wxGLContext * m_glRC
Detailed Description
Definition at line 30 of file operation.hpp.
Constructor & Destructor Documentation
TestGLCanvas()
TestGLCanvas::TestGLCanvas (wxWindow * parent, wxWindowID id = wxID_ANY, int * gl_attrib = NULL)
Definition at line 285 of file operation.cpp.
References m_glRC.
~TestGLCanvas()
TestGLCanvas::~TestGLCanvas () virtual
Definition at line 294 of file operation.cpp.
References m_glRC.
Member Function Documentation
InitGL()
void TestGLCanvas::InitGL ()
Definition at line 268 of file operation.cpp.
References m_glRC.
OnChar()
void TestGLCanvas::OnChar (wxKeyEvent & event)
Glut special key function.
Modify : trans
Definition at line 226 of file operation.cpp.
References myf, MyFrame::textbox_positionx, MyFrame::textbox_positiony, and trans.
OnMouseEvent()
void TestGLCanvas::OnMouseEvent (wxMouseEvent & event)
Glut mouse function.
Modify : cx, cy, scl
Definition at line 89 of file operation.cpp.
References linewidth, lmouse, myf, rot, scl, sx, sy, MyFrame::textbox_linewidth, MyFrame::textbox_positionx, MyFrame::textbox_positiony, MyFrame::textbox_rotatex, MyFrame::textbox_rotatey, MyFrame::textbox_rotatez, MyFrame::textbox_scale, thetax, thetay, thetaz, and trans.
OnPaint()
void TestGLCanvas::OnPaint (wxPaintEvent & event)
Glut Display function called by glutDisplayFunc.
Definition at line 554 of file draw.cpp.
References batch_name, draw_band, draw_bz_lines(), draw_circles(), draw_colorbar(), draw_fermi(), draw_fermi_line(), fbz, frmsf_file_name, lbatch, lcolorbar, lsection, lstereo, m_glRC, and scl.
OnSize()
void TestGLCanvas::OnSize (wxSizeEvent & event)
wxDECLARE_EVENT_TABLE()
TestGLCanvas::wxDECLARE_EVENT_TABLE () private
wxDECLARE_NO_COPY_CLASS()
TestGLCanvas::wxDECLARE_NO_COPY_CLASS (TestGLCanvas) private
Member Data Documentation
m_glRC
wxGLContext* TestGLCanvas::m_glRC private
Definition at line 46 of file operation.hpp.
Referenced by InitGL(), OnPaint(), TestGLCanvas(), and ~TestGLCanvas().
The documentation for this class was generated from the following files:
operation.hpp
draw.cpp
operation.cpp