fermisurfer: draw.cpp File Reference
draw.cpp File Reference
Functions for actual displaying.
#include "wx/wx.h"
#include "wx/glcanvas.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include "variable.hpp"
#include "operation.hpp"
Functions
static void draw_fermi ()
Draw Fermi surfaces.
static void draw_bz_lines ()
Draw lines of BZ boundaries.
static void draw_colorbar ()
Draw color-bar or colr-circle (periodic) as a color scale.
static void draw_circles (GLfloat dx2d)
Draw eye-points for the stereogram.
static void draw_fermi_line ()
Draw 2D Fermi lines.
Detailed Description
Functions for actual displaying.
Definition in file draw.cpp.
Function Documentation
draw_bz_lines()
static void draw_bz_lines () static
Draw lines of BZ boundaries.
Definition at line 218 of file draw.cpp.
References arrow, bvec, BZ_number, bzl, bzl2d, fbz, LineColor, linewidth, lsection, nbzl, nbzl2d, rot, SectionColor, secvec, sphere_v, and trans.
Referenced by TestGLCanvas::OnPaint().
draw_circles()
static void draw_circles (GLfloat dx2d) static
Draw eye-points for the stereogram.
Parameters
[in] dx2d [in] Translation used for the section-mode
Definition at line 493 of file draw.cpp.
References LineColor, and scl.
Referenced by TestGLCanvas::OnPaint().
draw_colorbar()
static void draw_colorbar () static
Draw color-bar or colr-circle (periodic) as a color scale.
Definition at line 355 of file draw.cpp.
References BackGroundColor, BarColor, bgray, blue, bvec, color_scale, cyan, green, linewidth, magenta, red, rot, wgray, and yellow.
Referenced by TestGLCanvas::OnPaint().
draw_fermi()
static void draw_fermi () static
Draw Fermi surfaces.
Modify : nmlp_rot, kvp_rot, kvnl_rot
First, rotate nmlp and kvp with OpenMP then draw them. Also draw nodeline in the same way.
Definition at line 50 of file draw.cpp.
References arw, arw_rot, black, bvec, BZ_number, clr, color_scale, draw_band, kveq, kveq_rot, kvnl, kvnl_rot, kvp, kvp_rot, lequator, nb, nequator, nmlp, nmlp_rot, nnl, nodeline, ntri, rot, side, and trans.
Referenced by TestGLCanvas::OnPaint().
draw_fermi_line()
static void draw_fermi_line () static
Draw 2D Fermi lines.
Definition at line 521 of file draw.cpp.
References bzl2d_proj, clr2d, draw_band, kv2d, LineColor, linewidth, n2d, nb, and nbzl2d.
Referenced by TestGLCanvas::OnPaint().