fermisurfer: free_patch.cpp File Reference
free_patch.cpp File Reference
Refresh patch.
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <omp.h>
#include <wx/wx.h>
#include <cmath>
#include "basic_math.hpp"
#include "menu.hpp"
#include "variable.hpp"
Functions
void free_patch ()
Free variables for patch before new patch is computed.
void max_and_min ()
Compute Max. & Min. of matrix elements. Compute color of each patch.
void paint ()
Compute Max. & Min. of matrix elements. Compute color of each patch.
Detailed Description
Refresh patch.
Definition in file free_patch.cpp.
Function Documentation
free_patch()
void free_patch ()
Free variables for patch before new patch is computed.
Free : nmlp, matp, clr, kvp, nmlp_rot, kvp_rot, kvnl, kvnl_rot, kv2d, clr2d
Definition at line 54 of file free_patch.cpp.
References arw, arw_rot, clr, clr2d, kv2d, kveq, kveq_rot, kvnl, kvnl_rot, kvp, kvp_rot, matp, nb, nequator, nmlp, nmlp_rot, nnl, ntri, refresh_equator, refresh_nodeline, refresh_patch, and refresh_section.
Referenced by MyFrame::button_compute(), and refresh_patch_segment().
max_and_min()
void max_and_min ()
Compute Max. & Min. of matrix elements. Compute color of each patch.
Modify : clr
Definition at line 132 of file free_patch.cpp.
References color_scale, get_thread(), matp, myf, nb, nmlp, nthreads, ntri, patch_max, patch_min, terminal, MyFrame::textbox_max, and MyFrame::textbox_min.
Referenced by compute_patch_segment().
paint()
void paint ()
Compute Max. & Min. of matrix elements. Compute color of each patch.
Modify : clr
Definition at line 288 of file free_patch.cpp.
References arw, BackGroundColor, BarColor, bgray, blue, clr, color_scale, cyan, green, kvp, magenta, matp, nb, nmlp, ntri, patch_max, patch_min, red, rgb_band, wgray, and yellow.
Referenced by compute_patch_segment(), MyFrame::radio_BarColor(), and MyFrame::textctrl_Band().