fermisurfer: initialize.hpp File Reference
initialize.hpp File Reference
Functions
void init_corner ()
Specify corners of tetrahedron.
void bragg_vector ()
Compute Bragg vetor.
void max_and_min_bz ()
Print max and minimum \(\varepsilon_{n k}, \Delta_{n k}\) in the whole Brillouine zone.
Function Documentation
bragg_vector()
void bragg_vector ()
Compute Bragg vetor.
Modify : bragg, brnrm
Definition at line 204 of file initialize.cpp.
References bragg, brnrm, brnrm_min, bvec, eigsort(), itet, ng0, and terminal.
Referenced by MyApp::OnInit().
init_corner()
void init_corner ()
Specify corners of tetrahedron.
Modify : corner
Definition at line 43 of file initialize.cpp.
References corner, and itet.
Referenced by MyApp::OnInit(), and MyFrame::radio_tetra().
max_and_min_bz()
void max_and_min_bz ()
Print max and minimum \(\varepsilon_{n k}, \Delta_{n k}\) in the whole Brillouine zone.
Definition at line 262 of file initialize.cpp.
References eig0, mat0, nb, ng0, and terminal.
Referenced by MyApp::OnInit().