fermisurfer: kumo.hpp File Reference
kumo.hpp File Reference
Functions
void interpol_energy ()
Interpolation of energy and matrix with the French-curve (Kumo) interpolation.
Function Documentation
interpol_energy()
void interpol_energy ()
Interpolation of energy and matrix with the French-curve (Kumo) interpolation.
Modify : eig, mat
Definition at line 66 of file kumo.cpp.
References avec, eig, eig0, interpol, kumo_coef(), mat, mat0, modulo(), nb, ng, ng0, terminal, and vf.
Referenced by compute_patch_segment(), and MyApp::OnInit().