fermisurfer: kumo.cpp File Reference
kumo.cpp File Reference
Compute \(\varepsilon_{n k}, \Delta_{n k}\) on denser \(k\)-grid with French-curve (Kumo) interpolation.
#include <wx/wx.h>
#include <cstdlib>
#include <cstdio>
#include "basic_math.hpp"
#include "variable.hpp"
Functions
static void kumo_coef (int j, GLfloat *coef, int interpol)
Compute coefficient for the French-curve (Kumo) interpolation.
void interpol_energy ()
Interpolation of energy and matrix with the French-curve (Kumo) interpolation.
Detailed Description
Compute \(\varepsilon_{n k}, \Delta_{n k}\) on denser \(k\)-grid with French-curve (Kumo) interpolation.
Definition in file kumo.cpp.
Function Documentation
interpol_energy()
void interpol_energy ()
Interpolation of energy and matrix with the French-curve (Kumo) interpolation.
Modify : eig, mat
Definition at line 66 of file kumo.cpp.
References avec, eig, eig0, interpol, kumo_coef(), mat, mat0, modulo(), nb, ng, ng0, terminal, and vf.
Referenced by compute_patch_segment(), and MyApp::OnInit().
kumo_coef()
static void kumo_coef (int j, GLfloat * coef, int interpol) static
Compute coefficient for the French-curve (Kumo) interpolation.
\[ A^{\rm intp} = \sum_{i = 1}^4 C_i A_i^{\rm orig} \]
Parameters
[in] j [in] Interpolated grid index
[out] coef [out] Coefficient of interpolation \(C_i\)
Definition at line 47 of file kumo.cpp.
References interpol.
Referenced by interpol_energy().