fermisurfer: menu.cpp File Reference
menu.cpp File Reference
Create & modify right-click menu. And operate their function.
#include "free_patch.hpp"
#include "fermi_patch.hpp"
#include "calc_nodeline.hpp"
#include "kumo.hpp"
#include "initialize.hpp"
#include "section.hpp"
#include "equator.hpp"
#include "draw.hpp"
#include "variable.hpp"
#include "menu.hpp"
#include "operation.hpp"
#include "fermisurfer.xpm"
#include <wx/splitter.h>
#include <wx/gbsizer.h>
#include <cstdlib>
#include <cstdio>
#include <cmath>
Enumerations
enum {
ibutton_reflesh, ibutton_compute, iradio_background, iradio_brillouinzone,
iradio_lighting, iradio_mouse, iradio_stereo, iradio_tetra,
iradio_colorscale, itext_colorscalemin, itext_colorscalemax, icheck_section,
icheck_gamma, itext_sectionx, itext_sectiony, itext_sectionz,
icheck_nodeline, icheck_colorbar, icheck_equator, itext_equatorx,
itext_equatory, itext_equatorz, itext_line, itext_shift,
itext_interpol, itext_scale, itext_positionx, itext_positiony,
itext_rotx, itext_roty, itext_rotz, ibutton_rotate,
itext_BackGroundR, itext_BackGroundG, itext_BackGroundB, itext_LineColorR,
itext_LineColorG, itext_LineColorB, iradio_BarColor, ibutton_section,
itext_BZ_number0, itext_BZ_number1, itext_BZ_number2, itext_SectionR,
itext_SectionG, itext_SectionB, itext_ArrowStart0, itext_ArrowStart1,
itext_ArrowStart2, itext_ArrowEnd0, itext_ArrowEnd1, itext_ArrowEnd2,
itext_ArrowDiff0, itext_ArrowDiff1, itext_ArrowDiff2, itext_sphereX,
itext_sphereY, itext_sphereZ, itext_sphereR, icheck_band
}
Functions
void compute_patch_segment ()
void refresh_patch_segment ()
Detailed Description
Create & modify right-click menu. And operate their function.
Definition in file menu.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ibutton_reflesh
ibutton_compute
iradio_background
iradio_brillouinzone
iradio_lighting
iradio_mouse
iradio_stereo
iradio_tetra
iradio_colorscale
itext_colorscalemin
itext_colorscalemax
icheck_section
icheck_gamma
itext_sectionx
itext_sectiony
itext_sectionz
icheck_nodeline
icheck_colorbar
icheck_equator
itext_equatorx
itext_equatory
itext_equatorz
itext_line
itext_shift
itext_interpol
itext_scale
itext_positionx
itext_positiony
itext_rotx
itext_roty
itext_rotz
ibutton_rotate
itext_BackGroundR
itext_BackGroundG
itext_BackGroundB
itext_LineColorR
itext_LineColorG
itext_LineColorB
iradio_BarColor
ibutton_section
itext_BZ_number0
itext_BZ_number1
itext_BZ_number2
itext_SectionR
itext_SectionG
itext_SectionB
itext_ArrowStart0
itext_ArrowStart1
itext_ArrowStart2
itext_ArrowEnd0
itext_ArrowEnd1
itext_ArrowEnd2
itext_ArrowDiff0
itext_ArrowDiff1
itext_ArrowDiff2
itext_sphereX
itext_sphereY
itext_sphereZ
itext_sphereR
icheck_band
Definition at line 94 of file menu.cpp.
Function Documentation
compute_patch_segment()
void compute_patch_segment ()
Definition at line 53 of file menu.cpp.
References calc_2dbz(), calc_nodeline(), calc_section(), equator(), fermi_patch(), interpol_energy(), max_and_min(), paint(), refresh_color, refresh_equator, refresh_interpol, refresh_nodeline, refresh_patch, refresh_section, and skip_minmax.
Referenced by MyFrame::button_compute(), MyApp::OnInit(), and refresh_patch_segment().
refresh_patch_segment()
void refresh_patch_segment ()
Definition at line 89 of file menu.cpp.
References compute_patch_segment(), and free_patch().
Referenced by batch_draw().