fermisurfer: menu.hpp File Reference
menu.hpp File Reference
#include "wx/wx.h"
#include "operation.hpp"
#include "wx/gbsizer.h"
#include "wx/splitter.h"
Classes
class MyFrame
Functions
void compute_patch_segment ()
void refresh_patch_segment ()
Function Documentation
compute_patch_segment()
void compute_patch_segment ()
Definition at line 53 of file menu.cpp.
References calc_2dbz(), calc_nodeline(), calc_section(), equator(), fermi_patch(), interpol_energy(), max_and_min(), paint(), refresh_color, refresh_equator, refresh_interpol, refresh_nodeline, refresh_patch, refresh_section, and skip_minmax.
Referenced by MyFrame::button_compute(), MyApp::OnInit(), and refresh_patch_segment().
refresh_patch_segment()
void refresh_patch_segment ()
Definition at line 89 of file menu.cpp.
References compute_patch_segment(), and free_patch().
Referenced by batch_draw().