fermisurfer: read_file.hpp File Reference
read_file.hpp File Reference
Functions
int read_file ()
Input from Fermi surface file.
void read_batch ()
void read_bxsf ()
Function Documentation
read_batch()
void read_batch ()
Definition at line 249 of file read_file.cpp.
References BackGroundColor, batch_name, color_scale, draw_band, EF, eqvec, fbz, interpol, itet, lcolorbar, lequator, LineColor, linewidth, lsection, lstereo, nb, nodeline, patch_max, patch_min, rot, scl, secscale, secvec, side, skip_minmax, terminal, Text2Lower(), thetax, thetay, thetaz, and trans.
Referenced by batch_draw().
read_bxsf()
void read_bxsf ()
Definition at line 408 of file read_file.cpp.
References allocate_griddata(), bvec, color_scale, EF, eig0, frmsf_file_name, nb, ng, ng0, shiftk, and terminal.
Referenced by MyApp::OnInit().
read_file()
int read_file ()
Input from Fermi surface file.
< Switch for shifted Brillouin zone
Definition at line 125 of file read_file.cpp.
References allocate_griddata(), bvec, eig0, frmsf_file_name, mat0, modulo(), nb, ng, ng0, shiftk, and terminal.
Referenced by MyApp::OnInit().