fermisurfer: read_file.cpp File Reference
read_file.cpp File Reference
Read .frmsf file.
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cctype>
#include <cstring>
#include "basic_math.hpp"
#include "variable.hpp"
#include <wx/wx.h>
Functions
static void allocate_griddata (int ng[3], int ng0[3])
int read_file ()
Input from Fermi surface file.
static void Text2Lower (char *value)
void read_batch ()
void read_bxsf ()
Detailed Description
Read .frmsf file.
Definition in file read_file.cpp.
Function Documentation
allocate_griddata()
static void allocate_griddata (int ng[3], int ng0[3]) static
Definition at line 46 of file read_file.cpp.
References avec, bvec, draw_band, eig, eig0, eqvec, eqvec_fr, linewidth, mat, mat0, myf, n2d, nb, nequator, ng, ng0, nnl, ntri, rgb_band, scl, secscale, secvec, secvec_fr, solve3(), terminal, MyFrame::textbox_linewidth, MyFrame::textbox_scale, and vf.
Referenced by read_bxsf(), and read_file().
read_batch()
void read_batch ()
Definition at line 249 of file read_file.cpp.
References BackGroundColor, batch_name, color_scale, draw_band, EF, eqvec, fbz, interpol, itet, lcolorbar, lequator, LineColor, linewidth, lsection, lstereo, nb, nodeline, patch_max, patch_min, rot, scl, secscale, secvec, side, skip_minmax, terminal, Text2Lower(), thetax, thetay, thetaz, and trans.
Referenced by batch_draw().
read_bxsf()
void read_bxsf ()
Definition at line 408 of file read_file.cpp.
References allocate_griddata(), bvec, color_scale, EF, eig0, frmsf_file_name, nb, ng, ng0, shiftk, and terminal.
Referenced by MyApp::OnInit().
read_file()
int read_file ()
Input from Fermi surface file.
< Switch for shifted Brillouin zone
Definition at line 125 of file read_file.cpp.
References allocate_griddata(), bvec, eig0, frmsf_file_name, mat0, modulo(), nb, ng, ng0, shiftk, and terminal.
Referenced by MyApp::OnInit().
Text2Lower()
static void Text2Lower (char * value) static
Parameters
[in,out] value [inout]
Definition at line 238 of file read_file.cpp.
Referenced by read_batch().