fermisurfer: section.hpp File Reference
section.hpp File Reference
Functions
void calc_2dbz ()
Compute boundary of 2D BZ.
void calc_section ()
Compute Fermi-line.
Function Documentation
calc_2dbz()
void calc_2dbz ()
Compute boundary of 2D BZ.
Modify : nbzl2d, bzl2d_proj
Definition at line 181 of file section.cpp.
References axis2d, bragg, bragg_vert2d(), brnrm, bzl2d, bzl2d_proj, fbz, nbragg, nbzl2d, proj_2d(), secscale, secvec, and set2daxis().
Referenced by compute_patch_segment(), and MyApp::OnInit().
calc_section()
void calc_section ()
Compute Fermi-line.
Modify : n2d, clr2d, kv2d
Definition at line 276 of file section.cpp.
References axis2d, clr, clr2d, eigsort(), fbz, get_thread(), kv2d, kvp, n2d, nb, nthreads, ntri, proj_2d(), secscale, secvec, and terminal.
Referenced by compute_patch_segment().