fermisurfer:fermisurfer.c
	gcc fermisurfer.c -fopenmp -O3 -lglut -lGLU -lGL -lm -o fermisurfer

install:
	sudo cp fermisurfer /usr/local/bin/fermisurfer

uninstall:
	sudo rm /usr/local/bin/fermisurfer

clean:
	rm fermisurfer

